### PR TITLE
Add some examples to the new structure

### PR DESCRIPTION
**Pull request by luanpotter**

### CODE REVIEW

**Review by erickzanardo — COMMENTED** [review]
The ported examples LGTM, but I think we should use Dashbook to build our menu rather than to build our own UI for that.

**Comment by spydon** [comment]
> The ported examples LGTM, but I think we should use Dashbook to build our menu rather than to build our own UI for that.

Hadn't you started to work on this already too @erickzanardo?

**Comment by erickzanardo** [comment]
> > The ported examples LGTM, but I think we should use Dashbook to build our menu rather than to build our own UI for that.
> 
> 
> 
> Hadn't you started to work on this already too @erickzanardo?

I had, but I have never finished, the branch got too old so I never went back on it.

I think what Luan made here is nice, even that ExampleDef class, if we change the ui manually done here for Dashbook stories and join with the structure already implemented, I think we are golden!

**Comment by luanpotter** [comment]
@erickzanardo I took a look at dashbook but it didn't seem to quite fit to what we want, it is basically a configurable playground for widgets, where here we just want a list of Games the player can play with. And then I thought of adding some other features that would only make sense here in the future. Maybe I am misunderstanding how dashbook works but it looked very tangent to this.

**Comment by erickzanardo** [comment]
It is both a showcase and a playground, so it is basically what we need here (the showcase part) and the playground is a bonus. We could for instance have examples where we could let the user change some properties and see how the game reacts in real-time, for example a particle example where you can change the number of particles being emitted, or the color of them, etc

**Comment by luanpotter** [comment]
I thought it would show the properties of the gamewidget to be configured, which is not what I wanted

**Comment by luanpotter** [comment]
I will merge this and then you can make a PR to show what it would look like @erickzanardo . I probably misunderstood how it works.

**Comment by erickzanardo** [comment]
> I thought it would show the properties of the gamewidget to be configured, which is not what I wanted

No, Dashbook properties are defined by the programmer, it don't do anything automatic, properties could even not be show when it don't make sense

**Pull request merged**
